### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Jaewin2002** [Dukka-De-La-Dokka/dokaka-web-early-r2#2]
Hello!  My name is Jaelyn and I just recently found your music through Bjork's song, Triumph of the Heart.  I think your work is amazing and I couldn't find you anywhere at all on the internet.  I made an account on this website just to make this message to hopefully reach you, but I probably will not go on the account again, if you get this message at any time I would love it if you possibly could reach out to me on my website, jaelynwingo.com.  I don't have a project or anything for you, but I am an artist and I would love to make you some paintings!  Do not worry if it takes you a while to see this, I understand:)
Thank you so much for reading!
Jaelyn Wingo
Jaelynwingo.com

**Comment by Jaewin2002** [comment]
@Dukka-De-La-Dokka  just in case I need to tag you!

**Comment by ghost** [comment]
Hi, I just have launched [new website](https://dokaka.com/), where you can find my contact. Thank you!
